name = "shadowsearch-youtube"
main = "src/index-simple.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8788
local_protocol = "http"

[ai]
binding = "AI"

# KV storage for video metadata and analysis results
[[kv_namespaces]]
binding = "YOUTUBE_VIDEOS"
id = "youtube-videos-namespace"
preview_id = "youtube-videos-preview"

# R2 storage for video files (commented for future implementation)
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "youtube-videos-storage"

[vars]
# Add any environment variables needed for YouTube processing
YOUTUBE_API_KEY = "AIzaSyBpIAcN5IIIcmfLwGq3j6fAV5QkW6vn4N0"
GEMINI_API_KEY = "AIzaSyBpIAcN5IIIcmfLwGq3j6fAV5QkW6vn4N0"
